Ext.define('Demo.model.github.Repo', {
    extend: 'Ext.data.Model',

    fields: [
        'id',
        'node_id',
        'name',
        'full_name',
        'private',
        'description',
        'homepage',
        'fork',
        'size',
        'language',
        'license',
        'forks',
        'watchers',
        'default_branch',
        { name: 'open_issues', type: 'number' },
        { name: 'stargazers_count', type: 'number' },
        { name: 'watchers_count', type: 'number' },
        { name: 'forks_count', type: 'number' },
        { name: 'open_issues_count', type: 'number' },
        { name: 'has_issues', type: 'boolean' },
        { name: 'has_projects', type: 'boolean' },
        { name: 'has_downloads', type: 'boolean' },
        { name: 'has_wiki', type: 'boolean' },
        { name: 'has_pages', type: 'boolean' },
        { name: 'archived', type: 'boolean' },
        { name: 'disabled', type: 'boolean' },
        { name: 'created_at', type: 'date' },
        { name: 'updated_at', type: 'date' },
        { name: 'pushed_at', type: 'date' },
        'url',
        'html_url',
        'forks_url',
        'mirror_url',
        'git_url',
        'ssh_url',
        'clone_url',
        'svn_url',
        'keys_url',
        'collaborators_url',
        'teams_url',
        'hooks_url',
        'issue_events_url',
        'events_url',
        'assignees_url',
        'branches_url',
        'tags_url',
        'blobs_url',
        'git_tags_url',
        'git_refs_url',
        'trees_url',
        'statuses_url',
        'languages_url',
        'stargazers_url',
        'contributors_url',
        'subscribers_url',
        'subscription_url',
        'commits_url',
        'git_commits_url',
        'comments_url',
        'issue_comment_url',
        'contents_url',
        'compare_url',
        'merges_url',
        'archive_url',
        'downloads_url',
        'issues_url',
        'pulls_url',
        'milestones_url',
        'notifications_url',
        'labels_url',
        'releases_url',
        'deployments_url'
    ],

    proxy: {
        type: 'rest',
        // url: 'https://api.github.com/users/sencha/repos',
        url: 'data/repos.json',
        reader: {
            type: 'json'
        }
    }
});